using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace CrossPrimitives.GodotAdapterGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class CpGlobalAliasesGenerator : IIncrementalGenerator
{
    private readonly static StringBuilder s_sb = new();

    private readonly static ImmutableArray<string> s_primitivesName = [
        "Vector2",
        "Vector2i",
        "Vector3",
        "Vector3i",
        "Vector4",
        "Vector4i",
        "Color",
    ]; 

    private readonly static string s_Prefix = "Cp";

    private static string GenerateCode()
    {
        s_sb.AppendLine("// <auto-generated/>");

        for (var i = 0; i < s_primitivesName.Length; i++)
        {
            var name = s_primitivesName[i];
            s_sb.AppendLine($"global using {s_Prefix}{name} = CrossPrimitives.{name};");
        }

        var code = s_sb.ToString();
        s_sb.Clear();

        return code;
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            var code = GenerateCode();

            ctx.AddSource(
                "CpGlobalAliases.g.cs",
                SourceText.From(code, Encoding.UTF8)
            );
        });
    }
}
